# Generated by Django 2.2.11 on 2020-03-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasosPorProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provincia', models.CharField(max_length=100)),
                ('Casos_positivos', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DatosCOVID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cerco', models.PositiveIntegerField(blank=True, default=0)),
                ('Casos_descartados', models.PositiveIntegerField(blank=True, default=0)),
                ('Casos_confirmados', models.PositiveIntegerField(blank=True, default=0)),
                ('Fallecidos', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
