# Generated by Django 2.2.11 on 2020-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscovid',
            name='Recuperados',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
