# Generated by Django 2.2.11 on 2020-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_datoscovid_recuperados'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscovid',
            name='Atualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
