# Generated by Django 2.2.11 on 2020-03-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_datoscovid_atualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscovid',
            old_name='Atualizado',
            new_name='Actualizado',
        ),
    ]
