# Generated by Django 2.2.11 on 2020-03-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_auto_20200330_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoscovid',
            name='Casos_descartados',
        ),
        migrations.AddField(
            model_name='datoscovid',
            name='En_domicilio',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='datoscovid',
            name='Hospitalizados_críticos',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='datoscovid',
            name='Hospitalizados_leves',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
